---
title: Complete Outdoor Solutions
baseurl: "/"
permalink: "/:title/"
palette: green
header:
  title: Complete Outdoor Solutions
  logo_img: "/images/cos-logo-long.png"
  has_nav: true
  menu:
    actions:
    - label: Get a Quote
      url: https://www.yardbook.com/new_quote/ac0e5ebab10a82086916a428017105da78dda1e8
footer:
  logo_img: "/images/cos-logo-long-1.png"
  tagline: Offering quality outdoor services to central Iowa
  has_nav: false
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: false
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Complete Outdoor Solutions 2020. All rights reserved."
  links:
  - text: Admin
    url: https://completeoutdoorsolutions.netlify.com/admin
    new_window: true
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
